<a href="https://colab.research.google.com/github/ejrtks1020/Pytorch-basic/blob/main/PyTorch_nnModule%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치의 nn.Linear와 nn.Sigmoid로 로지스틱 회귀 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [ ]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
model = nn.Sequential(
    nn.Linear(2, 1), # input_dim = 2, output_dim = 1
    nn.Sigmoid()
)

현재 W와 b는 랜덤 초기화 상태

In [ ]:
model(x_train)

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)

In [ ]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  hypothesis = model(x_train)

  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 10 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])  # 예측값이 0.5를 넘으면 True로 간주
    correct_prediction = prediction.float() == y_train  # 실제값과 일치하는 경우만 True로 간주
    print(correct_prediction.sum().item())
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
        epoch, nb_epochs, cost.item(), accuracy * 100,
    ))

4
Epoch    0/1000 Cost: 0.614994 Accuracy 66.67%
5
Epoch   10/1000 Cost: 0.747550 Accuracy 83.33%
5
Epoch   20/1000 Cost: 0.633216 Accuracy 83.33%
5
Epoch   30/1000 Cost: 0.538123 Accuracy 83.33%
5
Epoch   40/1000 Cost: 0.450406 Accuracy 83.33%
5
Epoch   50/1000 Cost: 0.366382 Accuracy 83.33%
5
Epoch   60/1000 Cost: 0.287368 Accuracy 83.33%
5
Epoch   70/1000 Cost: 0.219289 Accuracy 83.33%
6
Epoch   80/1000 Cost: 0.173225 Accuracy 100.00%
6
Epoch   90/1000 Cost: 0.151674 Accuracy 100.00%
6
Epoch  100/1000 Cost: 0.140280 Accuracy 100.00%
6
Epoch  110/1000 Cost: 0.131002 Accuracy 100.00%
6
Epoch  120/1000 Cost: 0.122903 Accuracy 100.00%
6
Epoch  130/1000 Cost: 0.115765 Accuracy 100.00%
6
Epoch  140/1000 Cost: 0.109426 Accuracy 100.00%
6
Epoch  150/1000 Cost: 0.103760 Accuracy 100.00%
6
Epoch  160/1000 Cost: 0.098664 Accuracy 100.00%
6
Epoch  170/1000 Cost: 0.094056 Accuracy 100.00%
6
Epoch  180/1000 Cost: 0.089870 Accuracy 100.00%
6
Epoch  190/1000 Cost: 0.086050 Accuracy 100.00%
6
Epoch 

In [ ]:
# 기존의 훈련데이터로 예측값 확인
model(x_train)

tensor([[2.8020e-04],
        [3.1770e-02],
        [3.9191e-02],
        [9.5600e-01],
        [9.9821e-01],
        [9.9968e-01]], grad_fn=<SigmoidBackward0>)

0.5를 넘으면 True, 그보다 낮으면 False로 간주, 실제값은 0, 0, 0, 1, 1, 1 이므로 전부 실제값과 일치한다

In [ ]:
#훈련후의 W와 b값 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2477, 1.5151]], requires_grad=True), Parameter containing:
tensor([-14.4576], requires_grad=True)]
