<a href="https://colab.research.google.com/github/ejrtks1020/Pytorch-basic/blob/main/Pytorch_nn_Module%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [ ]:
#데이터
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
#모델을 선언 및 초기화. 단순선형회귀이므로 inpud_dim = 1, output_dim = 1
model = nn.Linear(1, 1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [ ]:
# 전체 훈련데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

  # H(x) 계산
  prediction = model(X_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train)

  #cost로 H(x) 개선하는부분
  #gradient를 0으로 초기화
  optimizer.zero_grad()

  #비용 함수를 미분하여 gradient 계산
  cost.backward()
  #W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d} / {} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0 / 2000 Cost: 13.103541
Epoch  100 / 2000 Cost: 0.002791
Epoch  200 / 2000 Cost: 0.001724
Epoch  300 / 2000 Cost: 0.001066
Epoch  400 / 2000 Cost: 0.000658
Epoch  500 / 2000 Cost: 0.000407
Epoch  600 / 2000 Cost: 0.000251
Epoch  700 / 2000 Cost: 0.000155
Epoch  800 / 2000 Cost: 0.000096
Epoch  900 / 2000 Cost: 0.000059
Epoch 1000 / 2000 Cost: 0.000037
Epoch 1100 / 2000 Cost: 0.000023
Epoch 1200 / 2000 Cost: 0.000014
Epoch 1300 / 2000 Cost: 0.000009
Epoch 1400 / 2000 Cost: 0.000005
Epoch 1500 / 2000 Cost: 0.000003
Epoch 1600 / 2000 Cost: 0.000002
Epoch 1700 / 2000 Cost: 0.000001
Epoch 1800 / 2000 Cost: 0.000001
Epoch 1900 / 2000 Cost: 0.000000
Epoch 2000 / 2000 Cost: 0.000000


In [ ]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) #forward 연산

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters())) # W값이 2에 가깝고 b값이 0에 가깝다.

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


* 입력 x로 부터 예측된 y를 얻는 것을 forward연산이라고 한다
* 학습과정에서 비용함수를 미분하여 기울기를 구하는 것을 backward연산이라고 한다

#다중 선형 회귀 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# 모델을 선언 및 초기화, 다중 선형 회귀이므로 input_dim = 3, output_dim = 1
model = nn.Linear(3, 1)

In [ ]:
#모델에는 3개의 가중치 w와 편향 b가 저장되어 있음
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


W, b모두 랜덤초기화, 학습의 대상이므로 requires_grad = True가 되어있다

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  
  # H(x) 계산
  pred = model(x_train)
  # model(X_train)은 model.forward(X_train)과 동일하다.

  # cost 계산
  cost = F.mse_loss(pred, y_train) #평균 제곱 오차 함수

  # cost로 H(x)개선하는 부분
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  # W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost : {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost : 22642.416016
Epoch  100/2000 Cost : 4.976951
Epoch  200/2000 Cost : 4.733481
Epoch  300/2000 Cost : 4.502824
Epoch  400/2000 Cost : 4.284275
Epoch  500/2000 Cost : 4.077209
Epoch  600/2000 Cost : 3.881021
Epoch  700/2000 Cost : 3.695124
Epoch  800/2000 Cost : 3.519025
Epoch  900/2000 Cost : 3.352130
Epoch 1000/2000 Cost : 3.194023
Epoch 1100/2000 Cost : 3.044178
Epoch 1200/2000 Cost : 2.902206
Epoch 1300/2000 Cost : 2.767665
Epoch 1400/2000 Cost : 2.640176
Epoch 1500/2000 Cost : 2.519374
Epoch 1600/2000 Cost : 2.404892
Epoch 1700/2000 Cost : 2.296402
Epoch 1800/2000 Cost : 2.193589
Epoch 1900/2000 Cost : 2.096157
Epoch 2000/2000 Cost : 2.003828


In [ ]:
# 예측
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값에 대해 예측한 값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련후 입력이 73, 80, 75일 때의 예측값: ", pred_y)

훈련후 입력이 73, 80, 75일 때의 예측값:  tensor([[152.9719]], grad_fn=<AddmmBackward0>)


73, 80, 75은 훈련시 실제값 152였으므로 어느정도 3개의 W와 b값이 최적화 된것으로 보인다.

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.6294, 0.6883, 0.6936]], requires_grad=True), Parameter containing:
tensor([-0.0603], requires_grad=True)]
