<a href="https://colab.research.google.com/github/ejrtks1020/Pytorch-basic/blob/main/Pytorch_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 기본 세팅

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#2. 변수 선언

In [ ]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(X_train)
print(X_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


#3. 가중치와 편향의 초기화

In [ ]:
# 가중치 W, 편향 b를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [ ]:
#가설 세우기 : H(x) = Wx + b
hypothesis = X_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
# 비용 함수 선언하기
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
#경사 하강법 구현하기
optimizer = optim.SGD([W, b], lr = 0.01)

In [ ]:
nb_epochs = 1999 # 원하는 만큼 경사하강법을 반복
for epoch in range(nb_epochs + 1):
  # H(x)  계산
  hypothesis = X_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward() # 비용함수를 미분하여 gradient 계산
  optimizer.step() #W와 b를 업데이트

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))


Epoch    0/1999 W: 0.632, b: 0.270 Cost: 9.257346
Epoch  100/1999 W: 1.748, b: 0.574 Cost: 0.047480
Epoch  200/1999 W: 1.802, b: 0.451 Cost: 0.029340
Epoch  300/1999 W: 1.844, b: 0.355 Cost: 0.018130
Epoch  400/1999 W: 1.877, b: 0.279 Cost: 0.011203
Epoch  500/1999 W: 1.904, b: 0.219 Cost: 0.006923
Epoch  600/1999 W: 1.924, b: 0.172 Cost: 0.004278
Epoch  700/1999 W: 1.940, b: 0.135 Cost: 0.002644
Epoch  800/1999 W: 1.953, b: 0.106 Cost: 0.001634
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001009
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000624
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000385
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000238
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000147
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000091
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000056
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000021
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008


최종 훈련결과 최적의 기울기 W는 2에 가깝고 b는 0에 가깝다.

훈련 데이터 X_train이 [[1], [2], [3]]이고 y_train은 [[2],[4],[6]]인 것을 감안 하면 실제 정답은 W가 2이고 b가 0인 2x이므로 거의 정답을 찾음

In [ ]:
# optimizer.zero_grad() 가 필요한 이유
w = torch.tensor(2.0 ,requires_grad = True)
nb_epochs = 20
for epoch in range(nb_epochs):

  z = 2 * w
  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0


계속해서 미분값인 2가 누적되는것을 볼수 있다.
따라서 optimizer.zero_grad()를 통해 미분값을 계속 0으로 초기화 시켜줘야한다.

In [ ]:
# optimizer.zero_grad() 가 필요한 이유
w = torch.tensor(2.0 ,requires_grad = True)
optimizer = optim.SGD([w], lr = 0.01)
nb_epochs = 20
for epoch in range(nb_epochs):

  z = 2 * w
  optimizer.zero_grad()
  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0


#자동미분

모델이 복잡해질 수록 경사 하강법을 넘파이 등으로 직접 코딩하는 것은 까다로운 일이다. 파이토치에서는 이런 수고를 하지않도록 자동 미분을 지원한다.

In [ ]:
w = torch.tensor(2.0, requires_grad=True)

In [ ]:
y = w ** 2
z = 2 * y + 5 

이제 수식을 w에대해서 미분해야한다.
backward()를 호출하면 해당 수식의 w에대한 기울기를 계산한다.

In [ ]:
z.backward()

이제 w.grad를 출력하면 w가 속한 수식을 w로 미분한 값을  확인 할 수있다.

In [ ]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0
