<a href="https://colab.research.google.com/github/ejrtks1020/Pytorch-basic/blob/main/PyTorch_%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 파이토치로 단층 퍼셉트론 구현

In [ ]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.mannual_seed_all(777)

XOR 문제에 해당되는 입출력 정의

In [ ]:
X = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]]).to(device)
y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [ ]:
import torch.nn as nn

In [ ]:
linear = nn.Linear(2, 1, bias = True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)

0 또는 1을 예측하는 이진 분류 문제이므로 비용 함수로는 크로스 엔트로피 함수를 사용

In [ ]:
# 비용함수와 옵티마이저 정의
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 1)

In [ ]:
# 10,001번의 에포크 수행. 0번 에포크 부터 10,000번 에포크까지
for step in range(10001):
  optimizer.zero_grad()
  hypothesis = model(X)

  # 비용 함수
  cost = criterion(hypothesis, y)
  cost.backward()
  optimizer.step()

  if step % 100 == 0:
    print(step, cost.item())

0 0.7433513402938843
100 0.7433513402938843
200 0.7433513402938843
300 0.7433513402938843
400 0.7433513402938843
500 0.7433513402938843
600 0.7433513402938843
700 0.7433513402938843
800 0.7433513402938843
900 0.7433513402938843
1000 0.7433513402938843
1100 0.7433513402938843
1200 0.7433513402938843
1300 0.7433513402938843
1400 0.7433513402938843
1500 0.7433513402938843
1600 0.7433513402938843
1700 0.7433513402938843
1800 0.7433513402938843
1900 0.7433513402938843
2000 0.7433513402938843
2100 0.7433513402938843
2200 0.7433513402938843
2300 0.7433513402938843
2400 0.7433513402938843
2500 0.7433513402938843
2600 0.7433513402938843
2700 0.7433513402938843
2800 0.7433513402938843
2900 0.7433513402938843
3000 0.7433513402938843
3100 0.7433513402938843
3200 0.7433513402938843
3300 0.7433513402938843
3400 0.7433513402938843
3500 0.7433513402938843
3600 0.7433513402938843
3700 0.7433513402938843
3800 0.7433513402938843
3900 0.7433513402938843
4000 0.7433513402938843
4100 0.7433513402938843
4200

단층 퍼셉트론은 XOR문제를 풀 수 없기때문에 비용이 줄어들지 않는다.

# 2. 학습된 단층 퍼셉트론의 예측값 확인하기

In [ ]:
with torch.no_grad():
  hypothesis = model(X)
  predicted = (hypothesis > 0.5).float()
  accuracy = (predicted == y).float().mean()
  print('모델의 출력값(hypothesis):\n ', hypothesis.detach().cpu().numpy())
  print('모델의 예측값(Predicted):\n ', predicted.detach().cpu().numpy())
  print('실제값(Y):\n ', y.cpu().numpy())
  print('정확도(Accuracy): ', accuracy.item())

모델의 출력값(hypothesis):
  [[0.61287934]
 [0.61397755]
 [0.6849394 ]
 [0.68593794]]
모델의 예측값(Predicted):
  [[1.]
 [1.]
 [1.]
 [1.]]
실제값(Y):
  [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy):  0.5


# 3. 파이토치로 다층 퍼셉트론 구현하기

In [ ]:
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [ ]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [ ]:
# 다층 퍼셉트론 설게
model = nn.Sequential(
    nn.Linear(2, 10, bias = True), # input_layer = 2, hidden_layer1 = 10
    nn.Sigmoid(),

    nn.Linear(10, 10, bias = True), # hidden_layer1 = 10, hidden_layer2 = 10
    nn.Sigmoid(),

    nn.Linear(10, 10, bias = True), # hidden_layer2 = 10, hidden_layer3 = 10
    nn.Sigmoid(),

    nn.Linear(10, 1, bias = True), # hidden_layer3 = 10, output_layer = 1
    nn.Sigmoid()
).to(device)

In [ ]:
#비용함수와 옵티마이저 선언
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 1)

총 10001번의 에포크를 수행, 각 에포크마다 역전파가 수행된다.

In [ ]:
for epoch in range(10001):
  optimizer.zero_grad()

  #forward 연산
  hypothesis = model(X)

  #비용함수
  cost = criterion(hypothesis, Y)
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(epoch, cost.item())

0 0.6948983669281006
100 0.693155825138092
200 0.6931535601615906
300 0.6931513547897339
400 0.6931493282318115
500 0.6931473016738892
600 0.6931453943252563
700 0.6931434869766235
800 0.6931416988372803
900 0.6931397914886475
1000 0.6931379437446594
1100 0.6931361556053162
1200 0.6931343078613281
1300 0.6931324005126953
1400 0.6931304931640625
1500 0.6931284666061401
1600 0.6931264400482178
1700 0.6931242942810059
1800 0.6931220293045044
1900 0.6931197047233582
2000 0.6931172013282776
2100 0.6931145191192627
2200 0.6931115984916687
2300 0.6931084990501404
2400 0.6931051015853882
2500 0.6931014657020569
2600 0.6930974721908569
2700 0.6930930018424988
2800 0.6930879950523376
2900 0.6930825114250183
3000 0.6930762529373169
3100 0.6930692195892334
3200 0.6930611729621887
3300 0.6930519342422485
3400 0.6930411458015442
3500 0.6930283904075623
3600 0.6930132508277893
3700 0.6929951310157776
3800 0.6929728984832764
3900 0.6929452419281006
4000 0.6929103136062622
4100 0.6928649544715881
4200 

# 4. 학습된 다층 퍼셉트론의 예측값 확인하기:

In [ ]:
with torch.no_grad():
  hypothesis = model(X)
  predicted = (hypothesis > 0.5).float()
  accuracy = (predicted == Y).float().mean()
  print('모델의 출력값(hypothesis)', hypothesis)
  print('모델의 예측값(predicted)', predicted)
  print('실제값(Y):', Y)
  print('정확도(Accuracy)', accuracy.item())

모델의 출력값(hypothesis) tensor([[1.1169e-04],
        [9.9983e-01],
        [9.9984e-01],
        [1.8529e-04]])
모델의 예측값(predicted) tensor([[0.],
        [1.],
        [1.],
        [0.]])
실제값(Y): tensor([[0.],
        [1.],
        [1.],
        [0.]])
정확도(Accuracy) 1.0
