<a href="https://colab.research.google.com/github/ejrtks1020/Pytorch-basic/blob/main/pytorch_%ED%85%90%EC%84%9C_%EC%A1%B0%EC%9E%91_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t.dim())
print(t.shape)
print(t.size())


1
torch.Size([7])
torch.Size([7])


In [ ]:
t[:]

tensor([0., 1., 2., 3., 4., 5., 6.])

In [ ]:
t[3:], t[5:7], t[0], t[-1]

(tensor([3., 4., 5., 6.]), tensor([5., 6.]), tensor(0.), tensor(6.))

In [ ]:
t = torch.FloatTensor([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10]])
print(t)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


In [ ]:
print(t.dim())
print(t.size())

2
torch.Size([2, 5])


In [ ]:
print(t[:, 1])
print(t[:, 1].size())

tensor([2., 7.])
torch.Size([2])


In [ ]:
t[:, :-1]

tensor([[1., 2., 3., 4.],
        [6., 7., 8., 9.]])

In [ ]:
m1 = torch.FloatTensor([1, 2, 3])
m2 = torch.FloatTensor([4, 5, 6])
print(m1 + m2)

tensor([5., 7., 9.])


In [ ]:
m1 = torch.FloatTensor([2,3])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([5., 6.])


In [ ]:
# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1], [2]])
m2 = torch.FloatTensor([[3 ,4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
m1.size(), m2.size()

(torch.Size([2, 1]), torch.Size([1, 2]))

In [ ]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1.shape, m2.shape)
print(torch.matmul(m1, m2))

torch.Size([2, 2]) torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
print(m1 * m2)
print(torch.mul(m1, m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
print(m1.mean(), m2.mean())

tensor(2.5000) tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.mean(dim = 0))
print(t.mean(dim = 1))

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [ ]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
# Max , argmax
t = torch.FloatTensor([[1,2], [3,4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())
print(t.max(dim = 0)) #행방향 최댓값과 행방향 기준으로 최댓값의 인덱스
print(t.max(dim = 1))
print(t.max(dim = -1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
print(t.max(dim = 0)[0])
print(t.max(dim = 1)[0])
print(t.max(dim = -1)[0])

tensor([3., 4.])
tensor([2., 4.])
tensor([2., 4.])


In [ ]:
import numpy as np
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
#3차원 텐서를 2차원 텐서로 변경
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(ft.view([-1 , 1, 3]))
print(ft.view([-1, 1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
t = torch.FloatTensor([[0], [1], [2]])
print(t)
print(t.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
# 스퀴즈 - 1인 차원 제거
print(t.squeeze())
print(t.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# 언 스퀴즈 - 특정위치에 1인차원 추가
ft = torch.Tensor([1,2,3])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[1., 2., 3.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[1., 2., 3.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [ ]:
#연결 (concatenate)
x = torch.FloatTensor([[1,2] ,[3, 4]])
y = torch.FloatTensor([[5, 6], [7,8]])

In [ ]:
print(torch.cat([x,y], dim = 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
print(torch.cat([x,y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# 스택킹 Stacking
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x,y,z], dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#In-Place Operation 덮어쓰기 연산
x = torch.FloatTensor([[1,2], [3, 4]])

In [ ]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2.)) # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
